version: "3"

services:
  ssl-init:
    container_name: ssl-init
    image: debian:bullseye-slim
    volumes:
      - ssl_nginx:/certs/nginx
      - ssl_backend:/certs/backend
      - ./scripts:/scripts
    command: /bin/sh -c "apt-get update && apt-get install -y openssl && \
          chmod +x /scripts/generate_nginx_ssl.sh /scripts/generate_backend_ssl.sh && \
          /scripts/generate_nginx_ssl.sh && \
          /scripts/generate_backend_ssl.sh"


volumes:
  ssl_nginx:
    name: ssl_nginx
  ssl_backend:
    name: ssl_backend
