version: "3"

services:
  ssl-init:
    container_name: ssl-init
    build:
      context: .
      dockerfile: ./src/ssl-init/Dockerfile.prod
    volumes:
      - ssl_nginx:/certs/nginx
      - ssl_backend:/certs/backend
    networks:
      - app_network

  frontend:
    container_name: frontend
    build:
      context: ./src
      dockerfile: frontend/Dockerfile.prod
    env_file:
      - .env.prod
    volumes:
      - ssl_nginx:/etc/nginx/ssl
      - frontend_srcs:/var/www/html
      - static_data:/var/www/html/backend/static
      - image_data:/var/www/html/public/images
    ports:
      - "443:443"
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    container_name: backend
    build:
      context: ./src/backend
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
      - ./src/backend/.env.prod
    volumes:
      - static_data:/app/src/static
      - ssl_backend:/etc/backend/ssl
      - backend_srcs:/app
      - image_data:/app/src/images
    depends_on:
      - postgres
    networks:
      - db_network
      - app_network

  postgres:
    container_name: postgres
    build: ./src/postgres/
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - db_network
    depends_on:
      - ssl-init


volumes:
  postgres_data:
    name: postgres_data
  backend_srcs:
    name: backend_srcs
  frontend_srcs:
    name: frontend_srcs
  image_data:
    name: image_data
  static_data:
    name: static_data
  ssl_nginx:
    name: ssl_nginx
  ssl_backend:
    name: ssl_backend

networks:
  db_network:
    name: db_network
    driver: bridge
  app_network:
    name: app_network
    driver: bridge
